3DCytoFlow/src/3DCytoFlow/Controllers/AnalysesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using _3DCytoFlow.Models;
using _3DCytoFlow.ViewModels.Analysis;

namespace _3DCytoFlow.Controllers
{
    public class AnalysesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnalysesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Analyses
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = GetUser();
                var analysisViews = new List<AnalysisViewModel>();

                var analyses = _context.Analyses.Include(x => x.Patient).Include(x => x.User).Where(x => x.User.Id == user.Id).ToList();
                
                foreach ( var analysis in analyses )
                { 
                    var vm = _context.VirtualMachines.Include(i => i.Analysis).FirstOrDefault(i => i.Analysis.Id == analysis.Id);

                    var patient = analysis.Patient;

                    analysisViews.Add(new AnalysisViewModel
                    {
                        Id = analysis.Id,
                        UserId = analysis.User.Id,
                        UserFirstName = analysis.User.FirstName,
                        UserLastName = analysis.User.LastName,
                        PatientId = patient.Id,
                        PatientFirstName = patient.FirstName,
                        PatientLastName = patient.LastName,
                        Date = analysis.ResultDate,
                        ResultFilePath = analysis.ResultFilePath,
                        Etc = vm != null && string.IsNullOrWhiteSpace(analysis.ResultFilePath) ? vm.CompletionDate : null
                    });
                }

                return View(analysisViews);
            }

            return RedirectToAction("LogIn", "Account");
        }

        // GET: Analyses/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return HttpNotFound();
                }

                var analysis = _context.Analyses.Include(x => x.User).Single(m => m.Id == id);

                if (analysis == null)
                {
                    return HttpNotFound();
                }

                var userId = User.GetUserId();

                if (!analysis.User.Id.Equals(userId))
                {
                    ViewBag.errorMessage = "You don't have permission to do that";
                    return View("Error");
                }

                return View(analysis);
            }

            return RedirectToAction("LogIn", "Account");
        }

        // POST: Analyses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public IActionResult DeleteConfirmed(int id)
        {
            var analysis = _context.Analyses.Include(x => x.Clusters).Single(m => m.Id == id);

            //if user deletes an analysis with clusters
            foreach (var cluster in analysis.Clusters)
            {
                _context.Clusters.Remove(cluster);
            }

            var vm = _context.VirtualMachines.FirstOrDefault(i => i.Analysis.Id == analysis.Id);

            //if user deletes an analysis during process
            if (vm != null)
            {
                vm.Analysis = null;
                _context.VirtualMachines.Update(vm);
            }
           
            _context.Analyses.Remove(analysis);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        #region Helpers
        /// <summary>
        /// returns the current user
        /// </summary>
        /// <returns></returns>
        private ApplicationUser GetUser()
        {
            return _context.Users.First(i => i.UserName.Equals(User.Identity.Name));
        }
        #endregion
    }
}

3DCytoFlow/src/3DCytoFlow/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Microsoft.Extensions.OptionsModel;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Microsoft.WindowsAzure.Storage.RetryPolicies;
using Newtonsoft.Json;
using _3DCytoFlow.Models;
using _3DCytoFlow.Services;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace _3DCytoFlow.Controllers
{
    public class FileController : Controller
    {
        public UserManager<ApplicationUser> Manager { get; }
        private readonly ApplicationDbContext _context;
        private readonly string _storageConnectionString;
        private readonly ISmsSender _smsSender;
        private readonly string _sid;
        private readonly string _authToken;
        private readonly string _number;

        public FileController(ApplicationDbContext context, IOptions<StorageSettings> options, UserManager<ApplicationUser> userManager, ISmsSender smsSender, IOptions<SMSSettings> smsOptions)
        {
            Manager = userManager;
            _context = context;
            _smsSender = smsSender;
            _storageConnectionString = options.Value.StorageStringConnection;
            _sid = smsOptions.Value.Sid;
            _authToken = smsOptions.Value.Token;
            _number = smsOptions.Value.Number;
        }

        /// <summary>
        /// Returns login information for the vm from the web server
        /// </summary>
        /// <param></param>
        /// <param name="username"></param>
        /// <param name="psw"></param>
        /// <returns>LoginID?</returns>
        [HttpGet]
        [AllowAnonymous]
        public IActionResult GetToken([FromQuery]string username, string psw)
        {
            var vm = _context.VirtualMachines.First(x => x.MachineName == username);

            if (vm != null)
            {
                if (PasswordHash.ValidatePassword(psw, vm.HashedPassword))
                {
                    return Json(vm.Id);
                }
                return HttpBadRequest();
            }

            return HttpNotFound();
        }
        
        /// <summary>
        // gets vm id
        // assigns analysis that has no VM to that VM
        // gives the filepath of the .fcs file linked to that analysis
        /// </summary>
        /// <param name="vmId"></param>
        /// <returns></returns>
        [HttpGet]
        [AllowAnonymous]
        public ActionResult RequestAnalysis(string vmId)
        {
            var r = new RequestResponse();
            VirtualMachine vm;
            if (_context.VirtualMachines.Any(x => x.Id == vmId))
            {
                vm = _context.VirtualMachines.First(x => x.Id == vmId);
            }
            else
            {
                return HttpBadRequest();
            }

            // go through each analysis in the database and find the one that has a null virtual machine
            // return the filepath of the .fcs linked to that analysis

            // json object with found/notfound and the fcsFilePath
            // if found vm looks into it


            var analyses = _context.Analyses.Include(i => i.VirtualMachine);
            Analysis analysis = null;
            foreach (var a in analyses)
            {
                if (a.VirtualMachine == null && string.IsNullOrEmpty(a.ResultFilePath))
                {
                    analysis = a;
                    r.FileLocation = analysis.FcsFilePath;
                    r.Found = true;
                }
            }

            if (analysis != null)
            {
                vm.Analysis = analysis;
                _context.SaveChanges();
                r.Jobs = vm.Jobs;
                r.Points = vm.PointsToCalculate;

                return Json(r);
            }

            return Json(r);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult UpdateETC(string vmId, long? totalSeconds)
        {
            // Check if an analysis is found that matches vmID
            if (_context.VirtualMachines.Select(i => i.Analysis).Any(i => i.VirtualMachine.Id == vmId))
            {
                // if found then change the location to the given string and update the db
                var a = _context.VirtualMachines.Select(i => i.Analysis).First(i => i.VirtualMachine.Id == vmId);
                var analysis = _context.Analyses.Include(i => i.User).First(i => i.Id == a.Id);

                if( analysis != null )
                {
                    VirtualMachine vm = _context.VirtualMachines.First(i => i.Id == vmId);

                    if( totalSeconds != null )
                    {
                        int days = (int)totalSeconds / 60 / 60 / 24;
                        int hours = (int)(totalSeconds / 60 / 60) % 24;
                        int minutes = (int)(totalSeconds / 60) % 60;
                        int seconds = (int)(totalSeconds % 60);

                        vm.CompletionDate = DateTime.Now.Add(new TimeSpan(days, hours, minutes, seconds, 0));
                        _context.VirtualMachines.Update(vm);
                        _context.SaveChanges();

                        return Ok();
                    }
                    return HttpBadRequest();
                }
                return HttpBadRequest();
            }
            return HttpNotFound();
        }


        /// <summary>
        /// receive analysisID and loation
        /// check if the VM is linked that analyss
        /// if so, put the location into the analysis
        /// if not, then cry
        /// </summary>
        /// 
        [HttpGet]
        [AllowAnonymous]   
        public ActionResult AnalysisFinished(string vmId, string location)
        {

            Analysis analysis;
            // Check if an analysis is found that matches vmID
            if (_context.VirtualMachines.Select(i => i.Analysis).Any(i => i.VirtualMachine.Id == vmId))
            {
                // if found then change the location to the given string and update the db
                analysis = _context.VirtualMachines.Select(i => i.Analysis).FirstOrDefault(i => i.VirtualMachine.Id == vmId);

                if (analysis != null)
                {
                    var vm = _context.VirtualMachines.FirstOrDefault(i => i.Analysis.Id == analysis.Id);
                    vm.Analysis = null;

                    //TODO: Fix
                    vm.CompletionDate = null;

                    analysis.ResultFilePath = location;
                    _context.Analyses.Update(analysis);
                    _context.VirtualMachines.Update(vm);
                    _context.SaveChanges();

                    //send message to the user
                    var phone = "";
                    foreach (var user in _context.Users)
                    {
                        if (user.Analyses.FirstOrDefault(i => i.Id == analysis.Id) != null)
                        {
                            phone = user.Phone;
                        }
                    }

                    _smsSender.SendSms(new AuthMessageSender.Message{
                        Body = "Greetings" + "\nAn analysis that you recently requested has been completed"+ "\n" +
                               "Please, login to 3DCytoFlow to see the results\n"
                    }, _sid, _authToken, _number, phone);
                }

                // return something else here? Not sure what to return for working result
                return Ok();
            }
            // if the analysis does not exist
            // this should not be triggered
            return HttpBadRequest();
        }


        //
        // GET: /Account/UploadFile
        public ActionResult UploadFile()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = GetUser();

                var model = new UploadFileModel { Patients = _context.Patients.Where(x => x.User.UserName == user.UserName).ToArray() };

                return View(model);
            }

            return RedirectToAction("LogIn", "Account");
        }

        /// <summary>
        /// returns a patient with the provided name
        /// </summary>
        /// <param name="firstName"></param>
        /// <param name="lastName"></param>
        /// <returns></returns>
        private Patient GetPatient(string firstName, string lastName)
        {
            return _context.Patients.First(i => i.FirstName.Equals(firstName) && i.LastName.Equals(lastName));
        }

        /// <summary>
        /// Downloads all the json files from the storage and saves them in the Results folder
        /// </summary> 
        [HttpPost]
        public async Task<ActionResult> DownloadResult(string analysisId)
        {
            var analysis = _context.Analyses.FirstOrDefault(i => i.Id == int.Parse(analysisId));
            var vm = _context.VirtualMachines.Include(i => i.Analysis).FirstOrDefault(i => i.Analysis.Id == analysis.Id);

            if (analysis == null) return Json(false);

            var path = analysis.ResultFilePath;

            if (string.IsNullOrWhiteSpace(path) && vm != null) return Json(new {ETC = vm.CompletionDate});
            if (string.IsNullOrWhiteSpace(path) && vm == null) return Json(new {message = "Waiting to be analyzed"});

            var jsonString = "";
            //prepare container name
            var index = path.IndexOf('/');

            var containerName = path.Substring(0, index);

            //prepare blobName
            var blobName = path.Substring(index + 1);

            // Retrieve storage account from web.config

3DCytoFlow/src/3DCytoFlow/Views/Shared/LoginPartial.cshtml
@using System.Threading.Tasks
@using _3DCytoFlow.ViewModels.Account
@model LoginViewModel
@{
    ViewBag.Title = "Log in";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">@ViewBag.Title</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <div class="checkbox">
                                    @Html.CheckBoxFor(m => m.RememberMe)
                                    @Html.LabelFor(m => m.RememberMe)
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Log in" class="btn btn-default" />
                            </div>
                        </div>
                        <p>
                            @Html.ActionLink("Register as a new user", "Register", "Account")
                        </p>
                        <p>
                            @Html.ActionLink("Forgot password?", "ForgotPassword", "Account")
                        </p>
            }
        </section>
    </div>
</div>

3DCytoFlow/src/3DCytoFlow/Views/Shared/NavigationMenu.cshtml
@using System.Security.Claims
@*<script src="~/signalr/hubs"></script>*@
<script type="text/javascript">

    function showLoadingScreen() {
        $("#loading").fadeIn();
        var opts = {
            lines: 12, // The number of lines to draw
            length: 7, // The length of each line
            width: 4, // The line thickness
            radius: 10, // The radius of the inner circle
            color: '#000', // #rgb or #rrggbb
            speed: 1, // Rounds per second
            trail: 60, // Afterglow percentage
            shadow: false, // Whether to render a shadow
            hwaccel: false // Whether to use hardware acceleration
        };
        var target = document.getElementById('loading');
        var spinner = new Spinner(opts).spin(target);

        $("#loading").fadeIn();
    }

    $(document).ready(function () {
        $('#side-menu').metisMenu();
        if (!window.hasWebGL()) {
            $("#webGLMessage").show();
        }
    });

</script>

<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @if (User.Identity.IsAuthenticated)
            {
                @Html.ActionLink("3D CytoFlow", "Instructions", "Home", new {area = ""}, new {@class = "navbar-brand", @onclick = "showLoadingScreen()"})
            }
            else
            {
                @Html.ActionLink("3D CytoFlow", "Index", "Home", new {area = ""}, new {@class = "navbar-brand", @onclick = "showLoadingScreen()"})
            }
            <ul class="nav navbar-nav" style="display: none;" id="webGLMessage">
                <li><span class="pull-left text-danger" style="position: relative; top: 50%; transform: translateY(80%);">Sorry, it seems your system <a href="https://en.wikipedia.org/wiki/WebGL#Support" class="alert-link">does not support WebGL</a>. Please, use a different device.</span></li>
            </ul>
            <ul class="nav navbar-nav" id="newAnalysis" style="display: none;">
                <li><span class="pull-left text-info" style="position: relative; top: 50%; transform: translateY(80%);">A new analysis arrived! @Html.ActionLink("Click here to check it out!", "Index", "Analyses", null, new {onclick = "$('#newAnalysis').hide();"}) </span></li>
            </ul>
            <ul class="nav navbar-nav" id="warning-message">
                <li><span class="pull-left text-warning" style="position: relative; top: 50%; transform: translateY(80%);">Warning: this website is only viewable in landscape mode with tablet devices</span></li>
            </ul>
        </div>
        <!-- /.Loggin stuff -->
        <ul class="nav navbar-top-links navbar-right">
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <img src="~/images/user.png" class="img-responsive" alt="User"> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new {id = "logoutForm", @class = "navbar-right"}))
                            {
                                @Html.AntiForgeryToken()

                                <a href="javascript:document.getElementById('logoutForm').submit()" onclick="showLoadingScreen();"><img src="~/images/log_out.png" style="padding-top: 3px;" class="img-responsive" alt="Logout"> Log off</a>
                            }
                        }
                        else
                        {
                            <a href="@Url.Action("LogIn", "Account")" onclick="showLoadingScreen();" style="width: 150px; text-align: right; color: #337ab7;"><img style="padding-top: 3px;"src="~/images/log_in.png" class="img-responsive" alt="Login"> Login</a>
                        }
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a href="@Url.Action("Index", "Manage")" onclick="showLoadingScreen();" style="width: 150px; text-align: right; color: #337ab7;"><img style="height: 25px; padding-left: 5px; padding-top: 3px;" src="~/images/gear.png" class="img-responsive" alt="Settings"> Settings</a>
                        </li>
                    }
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        @if (User.IsSignedIn())
        {
            <style>
                .container {
                    width: calc(100% - 236px);
                    position: absolute;
                    margin-left: 236px;
                }
            </style>
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            @if (User.IsInRole("Admin"))
                            {
                                <a href="@Url.Action("Register", "Account")" onclick="showLoadingScreen()"><img src="~/images/user.png" class="img-responsive" alt="Register"> Register</a>
                            }
                        </li>
                        <li>
                            @if (User.IsInRole("Admin"))
                            {
                                <a href="@Url.Action("Index", "VirtualMachines")" onclick="showLoadingScreen()"><img src="~/images/virtual_machine.png" class="img-responsive" alt="Virtual Machines"> Virtual Machines</a>
                            }
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Patients")"><img src="~/images/family6464blue.png" class="img-responsive" alt="Patients"> Patients</a>
                            <ul class="nav">
                                <li>
                                    <a href="@Url.Action("Index", "Patients")" onclick="showLoadingScreen()"><img src="~/images/editblue6464.png" class="img-responsive" alt="Index"> Index</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Create", "Patients")" onclick="showLoadingScreen()"><img src="~/images/plus6464.png" class="img-responsive" alt="Add"/> Add</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Analyses")" onclick="showLoadingScreen()"><img src="~/images/chart_dot6464.png" class="img-responsive" alt="Results"> Analysis Results</a>
                        </li>
                        <li>
                            <a href="@Url.Action("UploadFile", "File")" onclick="showLoadingScreen()"><img src="~/images/upload6464blue.png" class="img-responsive" alt="Upload"> Upload Data</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
        }
        <!-- /.navbar-static-side -->
    </nav>
</div>

3DCytoFlow/src/3DCytoFlow/Views/Shared/ThankYou.cshtml
@{
    ViewBag.Title = "Thank you";
}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">@ViewBag.Title</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <h2 class="text-danger">Please, wait while we process your request.</h2>
          
</div>

3DCytoFlow/src/3DCytoFlow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3D CytoFlow</title>
    <script type="text/javascript">
        var appInsights = window.appInsights || function(config) {
            function s(config) {
                t[config] = function() {
                    var i = arguments;
                    t.queue.push(function() { t[config].apply(t, i) })
                }
            }

            var t = { config: config }, r = document, f = window, e = "script", o = r.createElement(e), i, u;
            for (o.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", r.getElementsByTagName(e)[0].parentNode.appendChild(o), t.cookie = r.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;)s("track" + i.pop());
            return config.disableExceptionTracking || (i = "onerror", s("_" + i), u = f[i], f[i] = function(config, r, f, e, o) {
                var s = u && u(config, r, f, e, o);
                return s !== !0 && t["_" + i](config, r, f, e, o), s
            }), t
        }({
            instrumentationKey: "cd0af4f0-c767-4266-9968-887461df8b4b"
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();

        function hasWebGL() {
            try {
                gl = canvas.getContext("webgl");
            } catch (x) {
                gl = null;
            }

            if (gl === null) {
                try {
                    gl = canvas.getContext("experimental-webgl");
                    glExperimental = true;
                } catch (x) {
                    gl = null;
                }
            }

            if (gl) {
                return true;
            } else if ("WebGLRenderingContext" in window) {
                return true;
            } // not a best way, as you're not 100% sure, so you can change it to false
            else {
                return false;
            }
        }
    </script>

    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/Site.css"/>
        <link rel="stylesheet" href="~/css/bootstrapValidator.min.css"/>
        <link rel="stylesheet" href="~/css/metisMenu.css"/>
        <link rel="stylesheet" href="~/css/timeline.css"/>
        <link rel="stylesheet" href="~/css/datepicker.css"/>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/modernizr-2.8.3.js"></script>
        <script src="~/js/spin.js"></script>
        <script src="~/js/respond.js"></script>
        <!-- Include the plugin's CSS and JS: -->
        <script type="text/javascript" src="~/js/bootstrap-multiselect.js"></script>
        <link rel="stylesheet" href="~/css/bootstrap-multiselect.css" type="text/css" />
    </environment>
    <script src="~/js/jquery.signalR.min.js"></script>
    <style>
        .container {
            width: 99%;
            position: absolute;
        }
        footer.container.body-content {
            position: absolute;
            margin-left: 0px;
        }
    </style>
</head>
<body>
    @*Render Navigation Menu*@
@{
    // Wait for the navigation menu to be loaded
    @await Html.PartialAsync("NavigationMenu");
}
<div id="loading">
    <div id="loadingcontent">
        <p id="loadingspinner">
            Loading...
        </p>
    </div>
</div>
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer class="container body-content">
            <p style="text-align: center; margin-top: 5px;">&copy; @DateTime.Now.Year - 3DCytoFlow</p>
        </footer>       
    </div>

    <environment names="Development,Staging,Production">       
        <script src="~/js/jquery-ui-1.10.2.js"></script>
        <script src="~/js/metisMenu.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/bootstrapValidator.min.js"></script>
        <script src="~/js/bootstrap-datepicker.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
    @RenderSection("styles", required: false)
</body>
</html>